C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\thermo_mechanical
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\mesh_generation
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\heat_diffusion
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\heat_diffusion\steady_state\2-d
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\heat_diffusion\steady_state
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\deformation_linear
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\deformation_linear\statics\2-d
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\common
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\common\graphics
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\deformation_nonlinear\statics\hyperelastic\3-d
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\deformation_nonlinear\statics\hyperelastic\3-d\Twisted_beam
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\deformation_nonlinear\statics\hyperelastic\3-d\Squash
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\deformation_nonlinear\statics\hyperelastic\3-d\Slit_plate
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\deformation_nonlinear\statics\hyperelastic\3-d\Line_load_cylinder
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\deformation_nonlinear\statics\hyperelastic\3-d\Curved_beam
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\deformation_nonlinear\statics\hyperelastic\3-d\Cook
C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\deformation_nonlinear\statics\hyperelastic
