% MATLAB Publish Configurations
% @version 1
% It is recommended that you do not edit this file directly, but use the
% Configuration Editor provided in MATLAB. Changes made to comments that
% exist outside of a configuration will not be saved.

%% @name Factory Default

publish_options.outputFileFormat='html';
publish_options.outputLocation='';
publish_options.styleSheet='';
publish_options.figureCaptureMethod='entireGUIWindow';
publish_options.imageFormat='default';
publish_options.useNewFigure=true;
publish_options.maxWidth=Inf;
publish_options.maxHeight=Inf;
publish_options.showCode=true;
publish_options.evaluateCode=true;
publish_options.catchError=true;
publish_options.createThumbnail=true;
publish_options.maxNumberOfOutputLines=Inf;

%% @name User Default

publish_options.outputFileFormat='html';
publish_options.outputLocation='';
publish_options.styleSheet='';
publish_options.figureCaptureMethod='entireGUIWindow';
publish_options.imageFormat='default';
publish_options.useNewFigure=true;
publish_options.maxWidth=Inf;
publish_options.maxHeight=Inf;
publish_options.showCode=true;
publish_options.evaluateCode=true;
publish_options.catchError=true;
publish_options.createThumbnail=true;
publish_options.maxNumberOfOutputLines=Inf;

%% @name pub_Floyd
%  @associatedFile C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\deformation_linear\statics\2-d\pub_Floyd.m
%  @mostRecentlyActioned true
%  @uniqueId 45f5674a:149ac27eb4b:-7fff
%  @publishOptionsBasedOn User Default

publish_options.outputFileFormat='html';
publish_options.outputLocation='';
publish_options.styleSheet='';
publish_options.figureCaptureMethod='entireGUIWindow';
publish_options.imageFormat='default';
publish_options.useNewFigure=true;
publish_options.maxWidth=Inf;
publish_options.maxHeight=Inf;
publish_options.showCode=true;
publish_options.evaluateCode=true;
publish_options.catchError=true;
publish_options.createThumbnail=true;
publish_options.maxNumberOfOutputLines=Inf;
publish_options.codeToEvaluate=[ ...
'% Modify expression to add input arguments.' char(10) ...
'% Example:' char(10) ...
'%   a = [1 2 3; 4 5 6]; ' char(10) ...
'%   foo(a);' char(10) ...
'' char(10) ...
'pub_Floyd' char(10) ...
]

publish('C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\deformation_linear\statics\2-d\pub_Floyd.m',publish_options);

%% @name pub_sin_rod_impl_2D_axi
%  @associatedFile C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\deformation_linear\dynamics\direct_implicit\2-d\pub_sin_rod_impl_2D_axi.m
%  @mostRecentlyActioned true
%  @uniqueId 45f5674a:149ac27eb4b:-7ffe
%  @publishOptionsBasedOn User Default

publish_options.outputFileFormat='html';
publish_options.outputLocation='';
publish_options.styleSheet='';
publish_options.figureCaptureMethod='entireGUIWindow';
publish_options.imageFormat='default';
publish_options.useNewFigure=true;
publish_options.maxWidth=Inf;
publish_options.maxHeight=Inf;
publish_options.showCode=true;
publish_options.evaluateCode=true;
publish_options.catchError=true;
publish_options.createThumbnail=true;
publish_options.maxNumberOfOutputLines=Inf;
publish_options.codeToEvaluate=[ ...
'% Modify expression to add input arguments.' char(10) ...
'% Example:' char(10) ...
'%   a = [1 2 3; 4 5 6]; ' char(10) ...
'%   foo(a);' char(10) ...
'' char(10) ...
'pub_sin_rod_impl_2D_axi' char(10) ...
]

publish('C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\deformation_linear\dynamics\direct_implicit\2-d\pub_sin_rod_impl_2D_axi.m',publish_options);

%% @name pub_T3NAFEMS
%  @associatedFile C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\heat_diffusion\transient\1-d\pub_T3NAFEMS.m
%  @mostRecentlyActioned true
%  @uniqueId 45f5674a:149ac27eb4b:-7ffd
%  @publishOptionsBasedOn User Default

publish_options.outputFileFormat='html';
publish_options.outputLocation='';
publish_options.styleSheet='';
publish_options.figureCaptureMethod='getframe';
publish_options.imageFormat='default';
publish_options.useNewFigure=true;
publish_options.maxWidth=Inf;
publish_options.maxHeight=Inf;
publish_options.showCode=true;
publish_options.evaluateCode=true;
publish_options.catchError=true;
publish_options.createThumbnail=true;
publish_options.maxNumberOfOutputLines=Inf;
publish_options.codeToEvaluate=[ ...
'% Modify expression to add input arguments.' char(10) ...
'% Example:' char(10) ...
'%   a = [1 2 3; 4 5 6]; ' char(10) ...
'%   foo(a);' char(10) ...
'' char(10) ...
'pub_T3NAFEMS' char(10) ...
]

publish('C:\Users\pkrysl\Documents\Research\Software folder\FEA software folder\fineale\examples\heat_diffusion\transient\1-d\pub_T3NAFEMS.m',publish_options);

