% <a href="matlab: doc 'fineale/algorithms/deformation_linear/Contents.m'">deformation_linear</a> - Mechanical deformation
% <a href="matlab: doc 'fineale/algorithms/deformation_nonlinear/Contents.m'">deformation_nonlinear</a> - Mechanical nonlinear deformation
% <a href="matlab: doc 'fineale/algorithms/general/Contents.m'">general</a> - Interpolation, extrapolation
% <a href="matlab: doc 'fineale/algorithms/graphics/Contents.m'">graphics</a> - Graphics
% <a href="matlab: doc 'fineale/algorithms/heat_diffusion/Contents.m'">heat_diffusion</a> - Heat diffusion
% <a href="matlab: doc 'fineale/algorithms/renumbering/Contents.m'">renumbering</a> - Renumbering of degrees of freedom
% <a href="matlab: doc 'fineale/algorithms/integrators/Contents.m'">integrators</a> - ODE integrators
% <a href="matlab: doc 'fineale/algorithms/rotations/Contents.m'">rotations</a> - Rotation in 3d
% <a href="matlab: doc 'fineale/algorithms/signals/Contents.m'">signals</a> - Signal processing
