% Test conversion of triangular elements into quadrilaterals.
% The circle circumference consists of two arcs, which are given centers
% slightly offset from the true center of the circle.  The mesh generator
% needs this to make sense of the orientation of the arcs.
h=2.8;
[fens,fes,groups,edge_fes,edge_groups]=targe2_mesher({...
    'curve 1 arc -12 0 0 -12 Center 0 0 ',...
    'curve 2 arc 0 -12 12 0 Center 0 0 ',...
    'curve 3 arc 12 0 0 12 Center 0 0 ',...
    'curve 4 arc 0 12 -12 0 Center 0 0 ',...
    ['subregion 1  property 1 boundary 1 2 3 4'],...
    ['m-ctl-point constant ' num2str(h)]
    }, 1.0);
 [fens,fes] = T3_to_Q4(fens,fes,[])
drawmesh({fens,fes},'fes');
view(2)
