% Test  triangular mesh generation  for arc-bounded domains.
h=2.8;
[fens,fes,groups,edge_fes,edge_groups]=targe2_mesher({...
    'curve 1 arc -12 0 12 0 Center 0 -8 rev',...
    'curve 2 arc 12 0 -12 0 Center 0 8 reversed',...
    ['subregion 1  property 1 boundary 1 2'],...
    ['m-ctl-point constant ' num2str(h)]
    }, 1.0);
drawmesh({fens,fes},'fes','facecolor', 'red');
view(2); pause(1)
[fens,fes,groups,edge_fes,edge_groups]=targe2_mesher({...
    'curve 1 arc -12 0 12 0 Center 0 -8 ',...
    'curve 2 arc 12 0 -12 0 Center 0 8 ',...
    ['subregion 1  property 1 boundary -1  -2 '],...
    ['m-ctl-point constant ' num2str(h)]
    }, 1.0);
drawmesh({fens,fes},'fes','facecolor', 'blue');
view(2); pause(1)
[fens,fes,groups,edge_fes,edge_groups]=targe2_mesher({...
    'curve 1 arc -12 0 12 0 Center 0 -8 rev',...
    'curve 2 arc 12 0 -12 0 Center 0 8 reversed',...
    'curve 3 arc -12 0 12 0 Center 0 -8 ',...
    'curve 4 arc 12 0 -12 0 Center 0 8 ',...
    ['subregion 1  property 1 boundary 1 2 hole 3 4 '],...
    ['m-ctl-point constant ' num2str(h)]
    }, 1.0);
drawmesh({fens,fes},'fes','facecolor', 'yellow');
view(2); pause(1)
[fens,fes,groups,edge_fes,edge_groups]=targe2_mesher({...
    'curve 1 arc -12 0 12 0 Center 0 -8 rev',...
    'curve 2 arc 12 0 -12 0 Center 0 8 reversed',...
    'curve 3 arc -12 0 12 0 Center 0 -8 ',...
    'curve 4 arc 12 0 -12 0 Center 0 8 ',...
    ['subregion 1  property 1 boundary 1 2 hole 3 4 '],...
    ['subregion 2 property 2 boundary -3 -4 '],...
    ['m-ctl-point constant ' num2str(h)]
    }, 1.0);
gv=drawmesh({fens,fes},'fes','facecolor', 'magenta');
view(2); pause(1)
nearest=fe_select(fens,fes,struct('nearestto',[2.3,-2]))
drawmesh({fens,subset(fes,nearest)},'gv', gv,'fes','facecolor', 'yellow');