% Domain of a circle with an error
% The circle circumference consists of four arcs.
% Note: an error was introduced on purpose into the definition of the domain below
% (the input is correct as "curve 2 arc 0 -12 12 0 Center 0 0").
h=2.8;
try
[fens,fes,groups,edge_fes,edge_groups]=targe2_mesher({...
    'curve 1 arc -12 0 0 -12 Center 0 0 ',...
    'curve 2 arc 0 -11 12 0 Center 0 0 ',...
    'curve 3 arc 12 0 0 12 Center 0 0 ',...
    'curve 4 arc 0 12 -12 0 Center 0 0 ',...
    ['subregion 1  property 1 boundary 1 2 3 4'],...
    ['m-ctl-point constant ' num2str(h)]
    }, 1.0);
drawmesh({fens,fes},'fes','shrink', 0.8);
view(2)
catch,end
