% Mesh of a rectangle.  An unstructured mesh.
%
% function [fens,fes] = T3_blocku(Length,Width,nL,nW,options)
%
% Range =<0,Length> x <0,Width>
% Divided into triangular (t3) elements: nL, nW in the first, second (x,y).
% This function  produces an unstructured mesh.
% options = Attributes recognized by the constructor of fe_T3.
% 
% Examples: 
%     [fens,fes] = T3_blocku(3.1,2.2,3,2,[]);
%     figure; drawmesh({fens,fes},'fes','facecolor','y'); hold on
%
% See the visual gallery by running test_block
% 
% See also:  T3_blocku, T3_cblock,  T3_crossblock, T3_ablock,
%            T3_ablockc, T3_ablockn, T3_block, T3_blockc, T3_blockn

function [fens,fes] = T3_blocku(Length,Width,nL,nW,options)
    if ~isstruct(options)
        other_dimension = options; clear options;
        options.other_dimension = other_dimension;
    end
    a=sqrt(2)/2;
    a=1;
    [fens,fes,groups,edge_fes,edge_groups]=targe2_mesher({...
            ['curve 1 line 0 0 ' num2str(nL) ' 0'],...
            ['curve 2 line ' num2str(nL) ' 0 ' num2str(nL) ' ' num2str(nW)],...
            ['curve 3 line ' num2str(nL) ' ' num2str(nW) ' 0 ' num2str(nW)],...
            ['curve 4 line 0 ' num2str(nW) ' 0 0'],...
            ['curve 11 line 0 0 ' num2str(nL/2) ' ' num2str(nW/2)],...
            ['curve 21 line ' num2str(nL) ' 0 ' num2str(nL/2) ' ' num2str(nW/2)],...
            ['curve 31 line ' num2str(nL) ' ' num2str(nW) ' ' num2str(nL/2) ' ' num2str(nW/2)],...
            ['curve 41 line 0 ' num2str(nW) ' ' num2str(nL/2) ' ' num2str(nW/2)],...
            ['subregion 1  property 1 boundary  1  2 3 4 11 -11 21 -21 31 -31 41 -41'],...
            ['m-ctl-point constant 1.0']
            }, options.other_dimension,options);
     fens = transform_apply(fens,@(x,d)(x.*[Length/nL,Width/nW]), {});   
end
% [fens,fes,groups,edge_fes,edge_groups]=targe2_mesher({...
%             ['curve 1 line 0 0 ' num2str(nL) ' 0'],...
%             ['curve 2 line ' num2str(nL) ' 0 ' num2str(nL) ' ' num2str(nW)],...
%             ['curve 3 line ' num2str(nL) ' ' num2str(nW) ' 0 ' num2str(nW)],...
%             ['curve 4 line 0 ' num2str(nW) ' 0 0'],...
%             ['fixed 1 xy ' num2str(nL/2) ' ' num2str(nW/2)],...
%             ['fixed 11 xy ' num2str(a) ' ' num2str(a)],...
%             ['fixed 22 xy ' num2str(nL-a) ' ' num2str(a)],...
%             ['fixed 33 xy ' num2str(nL-a) ' ' num2str(nW-a)],...
%             ['fixed 44 xy ' num2str(a) ' ' num2str(nW-a)],...
%             ['subregion 1  property 1 boundary  1  2 3 4'],...
%             ['m-ctl-point constant 1.0']
%             }, options.other_dimension,options);
%      
